#!/bin/sh
#
# @name ARCS Lab ARQ Project Rigid Drone
#
# @url to be added
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Zhichao Liu <zliu157@ucr.edu>
#
# @board px4_fmu-v5_default
# @board Pixhawk4_mini
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234


#We use 3S battery
param set-default BAT1_N_CELLS 3

param set-default IMU_GYRO_CUTOFF 120
param set-default IMU_DGYRO_CUTOFF 45

#disable safety switch set 0 when needed
param set-default CBRK_IO_SAFETY 22027

#PID tunning to be updated
param set-default MC_AIRMODE 1
param set-default MC_PITCHRATE_D 0.0012
param set-default MC_PITCHRATE_I 0.35
param set-default MC_PITCHRATE_MAX 1200
param set-default MC_PITCHRATE_P 0.082
param set-default MC_PITCH_P 8
param set-default MC_ROLLRATE_D 0.0012
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_MAX 1200
param set-default MC_ROLLRATE_P 0.076
param set-default MC_ROLL_P 8
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_MAX 600
param set-default MC_YAWRATE_P 0.25
param set-default MC_YAW_P 4

param set-default MPC_MANTHR_MIN 0
param set-default MPC_MAN_TILT_MAX 60
param set-default MPC_THR_CURVE 1
param set-default MPC_THR_HOVER 0.25
param set-default MPC_THR_MIN 0.05
param set-default MPC_Z_VEL_I_ACC 1.7

param set-default PWM_MAIN_MAX 1950
param set-default PWM_MAIN_MIN 1050

param set-default PWM_MAIN_RATE 0
param set-default THR_MDL_FAC 0.3
